Status on the Credito table is the objective

Model to preview if the clients will pay the loans

Clean and explore the data

In [6]:
# conda install anaconda::psycopg2
import psycopg2
import pandas as pd
import numpy as np

In [7]:
conexao = psycopg2.connect(
    host="192.168.0.135", database="mydb", user="postgres", password="postgres"
)

cursor = conexao.cursor()

In [8]:
sqlCreditos = 'SELECT * FROM "CREDITO"'

cursor.execute(sqlCreditos)

result = cursor.fetchall()

credito = pd.DataFrame(result, columns=[desc[0] for desc in cursor.description]) # type: ignore

credito.head()

IDCREDITO  Duracao  HistoricoCredito  Proposito  Valor  Investimentos  \
0          2       48                 2          1   5951              2   
1          3       12                 1          2   2096              2   
2          4       42                 2          3   7882              2   
3          5       24                 3          4   4870              2   
4          6       36                 2          2   9055              1   

   Emprego  TempoParcelamento  EstadoCivil  FiadorTerceiros  ResidenciaDesde  \
0      3.0                  2            1                3              2.0   
1      4.0                  2            4                3              3.0   
2      4.0                  2            4                4              4.0   
3      3.0                  3            4                3              4.0   
4      3.0                  2            4                3              4.0   

   Idade  OutrosFinanciamentos  Habitacao  EmprestimoExistente  Profissao  \
0     22                     3        1.0                    1          4   
1     49                     3        1.0                    1          3   
2     45                     3        2.0                    1          4   
3     53                     3        2.0                    2          4   
4     35                     3        2.0                    1          3   

   Dependentes  SocioEmpresa  Estrangeiro  Status  
0            1             0            0       0  
1            2             0            0       1  
2            2             0            0       1  
3            2             0            0       0  
4            2             1            0       1

### Clearing the data

In [9]:
credito.isnull().sum()

IDCREDITO                0
Duracao                  0
HistoricoCredito         0
Proposito                0
Valor                    0
Investimentos            0
Emprego                 10
TempoParcelamento        0
EstadoCivil              0
FiadorTerceiros          0
ResidenciaDesde          7
Idade                    0
OutrosFinanciamentos     0
Habitacao                9
EmprestimoExistente      0
Profissao                0
Dependentes              0
SocioEmpresa             0
Estrangeiro              0
Status                   0
dtype: int64

In [10]:
credito.loc[credito.Emprego.isna()]

# Profissao with 999 value???

IDCREDITO  Duracao  HistoricoCredito  Proposito  Valor  Investimentos  \
64           1        6                 0          1   1169              1   
134         78       11                 3          1   4771              2   
201        145       21                 1          3   2288              2   
983        960       24                 2          3   3069              5   
984         56        6                 5          4    783              1   
985        270       24                 2          1    999              1   
986        896       36                 3          5   8947              1   
987        199       24                 2          5   2760              1   
992         45       48                 1          5   6143              2   
993         95       12                 2          4   1318              4   

     Emprego  TempoParcelamento  EstadoCivil  FiadorTerceiros  \
64       NaN                  4            4                3   
134      NaN                  2            4                3   
201      NaN                  4            1                3   
983      NaN                  4            4                3   
984      NaN                  1            4                4   
985      NaN                  4            4                3   
986      NaN                  3            4                3   
987      NaN                  4            4                3   
992      NaN                  4            1                3   
993      NaN                  4            4                3   

     ResidenciaDesde  Idade  OutrosFinanciamentos  Habitacao  \
64               4.0     67                     3        1.0   
134              4.0     51                     3        1.0   
201              4.0     23                     3        NaN   
983              NaN     30                     3        2.0   
984              2.0     26                     2        1.0   
985              2.0     25                     3        1.0   
986              2.0     31                     2        1.0   
987              4.0     36                     1        NaN   
992              4.0     58                     2        2.0   
993              4.0     54                     3        1.0   

     EmprestimoExistente  Profissao  Dependentes  SocioEmpresa  Estrangeiro  \
64                     2          4            1             1            0   
134                    1          4            1             0            0   
201                    1          4            1             1            0   
983                    1          4            1             0            0   
984                    1          3            2             0            0   
985                    2          4            1             0            0   
986                    1          1            2             1            0   
987                    1          4            1             1            0   
992                    2        999            1             0            0   
993                    1        999            1             1            0   

     Status  
64        1  
134       1  
201       1  
983       1  
984       1  
985       1  
986       1  
987       1  
992       0  
993       1

In [11]:
credito.Emprego.fillna(0, inplace=True) # 0 means no information
credito.Emprego = credito.Emprego.astype(int)

In [12]:
credito.ResidenciaDesde.fillna(0, inplace=True) # 0 means no information
credito.ResidenciaDesde = credito.ResidenciaDesde.astype(int)

In [13]:
credito.Habitacao.fillna(0, inplace=True)  # 0 means no information
credito.Habitacao = credito.Habitacao.astype(int)

In [14]:
credito.isnull().sum()

IDCREDITO               0
Duracao                 0
HistoricoCredito        0
Proposito               0
Valor                   0
Investimentos           0
Emprego                 0
TempoParcelamento       0
EstadoCivil             0
FiadorTerceiros         0
ResidenciaDesde         0
Idade                   0
OutrosFinanciamentos    0
Habitacao               0
EmprestimoExistente     0
Profissao               0
Dependentes             0
SocioEmpresa            0
Estrangeiro             0
Status                  0
dtype: int64

In [15]:
credito.describe()

IDCREDITO      Duracao  HistoricoCredito    Proposito         Valor  \
count  1000.000000  1000.000000       1000.000000  1000.000000   1000.000000   
mean    500.500000    20.903000          1.999000     3.414000   3271.258000   
std     288.819436    12.058814          1.005988     2.033898   2822.736876   
min       1.000000     4.000000          0.000000     1.000000    250.000000   
25%     250.750000    12.000000          1.000000     1.000000   1365.500000   
50%     500.500000    18.000000          2.000000     3.000000   2319.500000   
75%     750.250000    24.000000          2.000000     5.000000   3972.250000   
max    1000.000000    72.000000          5.000000    10.000000  18424.000000   

       Investimentos      Emprego  TempoParcelamento  EstadoCivil  \
count    1000.000000  1000.000000        1000.000000  1000.000000   
mean        2.285000     2.677000           2.973000     2.878000   
std         1.133605     1.156723           1.118715     1.350904   
min         1.000000     0.000000           1.000000     1.000000   
25%         2.000000     2.000000           2.000000     1.000000   
50%         2.000000     3.000000           3.000000     4.000000   
75%         2.000000     3.000000           4.000000     4.000000   
max         5.000000     5.000000           4.000000     4.000000   

       FiadorTerceiros  ResidenciaDesde        Idade  OutrosFinanciamentos  \
count      1000.000000      1000.000000  1000.000000           1000.000000   
mean          3.011000         2.822000    35.546000              2.675000   
std           0.308178         1.124981    11.375469              0.705601   
min           1.000000         0.000000    19.000000              1.000000   
25%           3.000000         2.000000    27.000000              3.000000   
50%           3.000000         3.000000    33.000000              3.000000   
75%           3.000000         4.000000    42.000000              3.000000   
max           4.000000         4.000000    75.000000              3.000000   

         Habitacao  EmprestimoExistente    Profissao  Dependentes  \
count  1000.000000          1000.000000  1000.000000  1000.000000   
mean      1.448000             1.407000    12.273000     1.155000   
std       0.784801             0.577654    94.086358     0.362086   
min       0.000000             1.000000     1.000000     1.000000   
25%       1.000000             1.000000     3.000000     1.000000   
50%       1.000000             1.000000     4.000000     1.000000   
75%       2.000000             2.000000     4.000000     1.000000   
max       3.000000             4.000000   999.000000     2.000000   

       SocioEmpresa  Estrangeiro       Status  
count   1000.000000  1000.000000  1000.000000  
mean       0.404000     0.037000     0.700000  
std        0.490943     0.188856     0.458487  
min        0.000000     0.000000     0.000000  
25%        0.000000     0.000000     0.000000  
50%        0.000000     0.000000     1.000000  
75%        1.000000     0.000000     1.000000  
max        1.000000     1.000000     1.000000

In [16]:
credito.Profissao.unique()

array([  4,   3,   1,   2, 999])

In [17]:
credito.Profissao.loc[credito.Profissao == 999] = 0

In [18]:
credito.Profissao.unique()

array([4, 3, 1, 2, 0])

In [19]:
credito.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   IDCREDITO             1000 non-null   int64
 1   Duracao               1000 non-null   int64
 2   HistoricoCredito      1000 non-null   int64
 3   Proposito             1000 non-null   int64
 4   Valor                 1000 non-null   int64
 5   Investimentos         1000 non-null   int64
 6   Emprego               1000 non-null   int64
 7   TempoParcelamento     1000 non-null   int64
 8   EstadoCivil           1000 non-null   int64
 9   FiadorTerceiros       1000 non-null   int64
 10  ResidenciaDesde       1000 non-null   int64
 11  Idade                 1000 non-null   int64
 12  OutrosFinanciamentos  1000 non-null   int64
 13  Habitacao             1000 non-null   int64
 14  EmprestimoExistente   1000 non-null   int64
 15  Profissao             1000 non-null   int64
 16  Depende

### Naive Bayes

In [20]:
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix, accuracy_score

In [21]:
credito.drop(columns=["IDCREDITO"], inplace=True)

In [22]:
credito.shape

(1000, 19)

In [23]:
previsores = credito.iloc[:, 0:18].values
classe = credito.iloc[:, 18].values

In [24]:
previsores

array([[48,  2,  1, ...,  1,  0,  0],
       [12,  1,  2, ...,  2,  0,  0],
       [42,  2,  3, ...,  2,  0,  0],
       ...,
       [18,  0,  1, ...,  1,  0,  0],
       [ 6,  0, 10, ...,  2,  1,  0],
       [24,  0,  6, ...,  1,  1,  0]])

In [25]:
X_Treino, X_Teste, Y_Treino, Y_Teste = train_test_split(
    previsores, classe, test_size=0.3, random_state=0
)

In [26]:
naive_bayes = GaussianNB()
naive_bayes.fit(X_Treino, Y_Treino)

GaussianNB()

In [27]:
previsoes = naive_bayes.predict(X_Teste)

In [28]:
confusao = confusion_matrix(Y_Teste, previsoes)
confusao

array([[ 40,  35],
       [ 43, 182]])

In [29]:
taxa_acerto = accuracy_score(Y_Teste, previsoes)
taxa_acerto

0.74

In [30]:
print("Accuracy: {:.2f}%".format(taxa_acerto * 100))

Accuracy: 74.00%


### Random Forest

In [31]:
from sklearn.ensemble import RandomForestClassifier

In [32]:
previsores = credito.iloc[:, 0:18].values
classe = credito.iloc[:, 18].values

In [33]:
X_Treino, X_Teste, Y_Treino, Y_Teste = train_test_split(
    previsores, classe, test_size=0.3, random_state=0
)

In [34]:
forest = RandomForestClassifier(n_estimators=100)
forest.fit(X_Treino, Y_Treino)

RandomForestClassifier()

In [35]:
previsao = forest.predict(X_Teste)

confusao = confusion_matrix(Y_Teste, previsao)

taxa_acerto = accuracy_score(Y_Teste, previsao)

print("Accuracy: {:.2f}%".format(taxa_acerto * 100))

Accuracy: 76.67%


### Neural Network

In [36]:
from keras.models import Sequential
from keras.layers import Dense
from sklearn.preprocessing import StandardScaler
from sklearn.compose import make_column_transformer

In [37]:
previsores = credito.iloc[:, 0:18].values
classe = credito.iloc[:, 18].values

In [54]:
X_Treino, X_Teste, Y_Treino, Y_Teste = train_test_split(
    previsores, classe, test_size=0.2, random_state=0
)

In [55]:
# Normalizing the data
sc = StandardScaler()

X_Treino = sc.fit_transform(X_Treino)
X_Teste = sc.transform(X_Teste)

In [74]:
classifier = Sequential()

# Adding the input layer and the first hidden layer
classifier.add(Dense(units=9, activation="relu", kernel_initializer="uniform", input_dim=18))

# Adding the second hidden layer
classifier.add(Dense(units=9, activation="relu", kernel_initializer="uniform"))

# Adding the output layer
classifier.add(Dense(units=1, activation="sigmoid"))

# Compiling the ANN
classifier.compile(optimizer="adam", loss="binary_crossentropy", metrics=["accuracy"])

# Training the ANN
classifier.fit(X_Treino, Y_Treino, batch_size=10, epochs=100)

Epoch 1/100


/opt/conda/lib/python3.12/site-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


80/80 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6616 - loss: 0.6858
Epoch 2/100
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7038 - loss: 0.6404
Epoch 3/100
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6960 - loss: 0.5783
Epoch 4/100
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7181 - loss: 0.5457
Epoch 5/100
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7292 - loss: 0.5407
Epoch 6/100
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7385 - loss: 0.5514  
Epoch 7/100
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7554 - loss: 0.5102  
Epoch 8/100
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7419 - loss: 0.5347
Epoch 9/100
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7476 - loss: 0.5108
Epoch 10/100
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7782 - loss: 0.4914
Epoch 11/100
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7541 - loss: 0.5187  
Epoch 12/100
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.733

In [75]:
Y_prediction = classifier.predict(X_Teste)
Y_prediction = Y_prediction > 0.5

7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step 


In [76]:
confusao = confusion_matrix(Y_Teste, Y_prediction)

taxa_acerto = accuracy_score(Y_Teste, Y_prediction)

print("Accuracy: {:.2f}%".format(taxa_acerto * 100))

Accuracy: 73.50%
