In [21]:
from sklearn import datasets
import numpy as np
from sklearn.metrics import confusion_matrix
import skfuzzy

In [22]:
iris = datasets.load_iris()

In [23]:
# Fuzzy c-means
r = skfuzzy.cmeans(data=iris.data.T, c=3, m=2, error=0.005, maxiter=1000, init=None)

In [24]:
previsoes_porcentagem = r[1]
previsoes_porcentagem[0][0]

0.996623647515751

In [25]:
for x in range(150):
    print(iris.target[x])
    print(previsoes_porcentagem[0][x])
    print(previsoes_porcentagem[1][x])
    print(previsoes_porcentagem[2][x])
    print('---')

0
0.996623647515751
0.002304461712432643
0.001071890771816247
---
0
0.975834504362586
0.016663043233788553
0.007502452403625578
---
0
0.9798141696268257
0.013768339997081507
0.006417490376092829
---
0
0.9674035518957924
0.02248300386729088
0.010113444236916654
---
0
0.9944699241689651
0.003762197971930337
0.001767877859104528
---
0
0.9345355297024867
0.04483449489990132
0.020629975397611917
---
0
0.9794794578309497
0.014012963105501658
0.0065075790635486875
---
0
0.999546934422112
0.000311776908671085
0.00014128866921706953
---
0
0.930334284877971
0.047752119366445425
0.021913595755583555
---
0
0.9827093488954102
0.011945672166129242
0.005344978938460728
---
0
0.9680254838792449
0.021769202688631854
0.010205313432123348
---
0
0.9921304096963752
0.005436785701346796
0.0024328046022780115
---
0
0.9706196929225813
0.020198063799435208
0.009182243277983346
---
0
0.922928572575131
0.051824857752563756
0.025246569672305298
---
0
0.8897144607562009
0.07264051500824636
0.03764502423555278
---


In [26]:
previsoes = previsoes_porcentagem.argmax(axis=0)
resultados = confusion_matrix(iris.target, previsoes)
print(resultados)

[[50  0  0]
 [ 0 47  3]
 [ 0 13 37]]


In [27]:
taxa_acerto = np.sum(np.diagonal(resultados)) / np.sum(resultados)
print(taxa_acerto)

0.8933333333333333
