In [24]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt

plt.rcParams["font.family"] = "serif"

from sklearn.linear_model import LinearRegression

import statsmodels.formula.api as smf

In [25]:
base = pd.read_csv("../data/mt_cars.csv")

base.head(10)

Unnamed: 0   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
0          Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4   
1      Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4   
2         Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4   
3     Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3   
4  Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3   
5            Valiant  18.1    6  225.0  105  2.76  3.460  20.22   1   0     3   
6         Duster 360  14.3    8  360.0  245  3.21  3.570  15.84   0   0     3   
7          Merc 240D  24.4    4  146.7   62  3.69  3.190  20.00   1   0     4   
8           Merc 230  22.8    4  140.8   95  3.92  3.150  22.90   1   0     4   
9           Merc 280  19.2    6  167.6  123  3.92  3.440  18.30   1   0     4   

   carb  
0     4  
1     4  
2     1  
3     1  
4     2  
5     1  
6     4  
7     2  
8     2  
9     4

In [26]:
base.shape

(32, 12)

In [27]:
base = base.drop("Unnamed: 0", axis=1)

In [28]:
base.head(10)

mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
0  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4     4
1  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4     4
2  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4     1
3  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3     1
4  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3     2
5  18.1    6  225.0  105  2.76  3.460  20.22   1   0     3     1
6  14.3    8  360.0  245  3.21  3.570  15.84   0   0     3     4
7  24.4    4  146.7   62  3.69  3.190  20.00   1   0     4     2
8  22.8    4  140.8   95  3.92  3.150  22.90   1   0     4     2
9  19.2    6  167.6  123  3.92  3.440  18.30   1   0     4     4

In [29]:
X = base.iloc[:, 2].values  # Disp
y = base.iloc[:, 0].values  # MPG

correlacao = np.corrcoef(X, y)
correlacao

array([[ 1.        , -0.84755138],
       [-0.84755138,  1.        ]])

In [30]:
X = X.reshape(-1, 1)

In [31]:
modelo = LinearRegression()
modelo.fit(X, y)

LinearRegression()

In [32]:
# Onde a linha intercepta o eixo y

modelo.intercept_

29.59985475616395

In [33]:
# Inclinação
modelo.coef_

array([-0.04121512])

In [34]:
# R²
# R² = 1 - (SQres / SQtotal)
# Determina o quanto o modelo consegue explicar o que acontece

modelo.score(X, y)

0.7183433404897299

In [35]:
previsoes = modelo.predict(X)
previsoes

array([23.00543556, 23.00543556, 25.1486218 , 18.96635381, 14.76241157,
       20.32645276, 14.76241157, 23.55359666, 23.79676587, 22.69220065,
       22.69220065, 18.23272467, 18.23272467, 18.23272467, 10.14631813,
       10.64089957, 11.46520197, 26.35622482, 26.47987017, 26.66945973,
       24.64991885, 16.49344661, 17.07045829, 15.17456277, 13.11380677,
       26.34386028, 24.64167582, 25.68029685, 15.13334765, 23.62366236,
       17.19410365, 24.61282524])

In [36]:
modelo_ajustado = smf.ols(formula="mpg ~ disp", data=base)
modelo_treinado = modelo_ajustado.fit()
modelo_treinado.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                    mpg   R-squared:                       0.718
Model:                            OLS   Adj. R-squared:                  0.709
Method:                 Least Squares   F-statistic:                     76.51
Date:                Tue, 04 Jun 2024   Prob (F-statistic):           9.38e-10
Time:                        00:37:05   Log-Likelihood:                -82.105
No. Observations:                  32   AIC:                             168.2
Df Residuals:                      30   BIC:                             171.1
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     29.5999      1.230     24.070      0.000      27.088      32.111
disp          -0.0412      0.005     -8.747      0.000      -0.051      -0.032
==============================================================================
Omnibus:                        3.368   Durbin-Watson:                   1.250
Prob(Omnibus):                  0.186   Jarque-Bera (JB):                3.049
Skew:                           0.719   Prob(JB):                        0.218
Kurtosis:                       2.532   Cond. No.                         558.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [37]:
plt.scatter(X, y)
plt.plot(X, previsoes, color="red")

In [38]:
modelo.predict([[200]])

array([21.35683076])

In [39]:
X1 = base.iloc[:, 1:4].values
y1 = base.iloc[:, 0].values

# Fist 10 rows
X1[10:]

array([[  6. , 167.6, 123. ],
       [  8. , 275.8, 180. ],
       [  8. , 275.8, 180. ],
       [  8. , 275.8, 180. ],
       [  8. , 472. , 205. ],
       [  8. , 460. , 215. ],
       [  8. , 440. , 230. ],
       [  4. ,  78.7,  66. ],
       [  4. ,  75.7,  52. ],
       [  4. ,  71.1,  65. ],
       [  4. , 120.1,  97. ],
       [  8. , 318. , 150. ],
       [  8. , 304. , 150. ],
       [  8. , 350. , 245. ],
       [  8. , 400. , 175. ],
       [  4. ,  79. ,  66. ],
       [  4. , 120.3,  91. ],
       [  4. ,  95.1, 113. ],
       [  8. , 351. , 264. ],
       [  6. , 145. , 175. ],
       [  8. , 301. , 335. ],
       [  4. , 121. , 109. ]])

In [40]:
modelo2 = LinearRegression()
modelo2.fit(X1, y1)

# R²
modelo2.score(X1, y1)

0.7678877440928638

In [41]:
modelo_ajustado2 = smf.ols(formula="mpg ~ cyl + disp + hp", data=base)
modelo_treinado2 = modelo_ajustado2.fit()
modelo_treinado2.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                    mpg   R-squared:                       0.768
Model:                            OLS   Adj. R-squared:                  0.743
Method:                 Least Squares   F-statistic:                     30.88
Date:                Tue, 04 Jun 2024   Prob (F-statistic):           5.05e-09
Time:                        00:37:05   Log-Likelihood:                -79.009
No. Observations:                  32   AIC:                             166.0
Df Residuals:                      28   BIC:                             171.9
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     34.1849      2.591     13.195      0.000      28.878      39.492
cyl           -1.2274      0.797     -1.540      0.135      -2.861       0.406
disp          -0.0188      0.010     -1.811      0.081      -0.040       0.002
hp            -0.0147      0.015     -1.002      0.325      -0.045       0.015
==============================================================================
Omnibus:                        2.942   Durbin-Watson:                   1.606
Prob(Omnibus):                  0.230   Jarque-Bera (JB):                2.558
Skew:                           0.675   Prob(JB):                        0.278
Kurtosis:                       2.692   Cond. No.                     1.51e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.51e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [44]:
# Cylinder, Disp, HP
novo = np.array([4, 200, 100])

novo = novo.reshape(1, -1)
modelo2.predict(novo)

array([24.03968887])