In [1]:
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from keras.models import Sequential
from keras.layers import Dense
from keras.utils import np_utils
import numpy as np

2024-06-21 13:05:10.862389: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: SSE4.1 SSE4.2 AVX AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [2]:
base = datasets.load_iris()
previsores = base.data
classe = base.target

classe

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [3]:
class_dummy = np_utils.to_categorical(classe)
class_dummy

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [4]:
X_treinamento, X_teste, y_treinamento, y_teste = train_test_split(
    previsores, class_dummy, test_size=0.3, random_state=0
)

In [5]:
modelo = Sequential()

modelo.add(Dense(units=5, input_dim=4))
modelo.add(Dense(units=4))
modelo.add(Dense(units=3, activation='softmax'))

2024-06-21 13:34:10.654623: I tensorflow/core/common_runtime/process_util.cc:146] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.


In [6]:
modelo.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 5)                 25        
                                                                 
 dense_1 (Dense)             (None, 4)                 24        
                                                                 
 dense_2 (Dense)             (None, 3)                 15        
                                                                 
Total params: 64
Trainable params: 64
Non-trainable params: 0
_________________________________________________________________


In [7]:
modelo.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

modelo.fit(X_treinamento, y_treinamento, epochs=1000, validation_data=(X_teste, y_teste))

Epoch 1/1000
4/4 [==============================] - 1s 142ms/step - loss: 6.3684 - accuracy: 0.3238 - val_loss: 5.6402 - val_accuracy: 0.3556
Epoch 2/1000
4/4 [==============================] - 0s 69ms/step - loss: 6.0400 - accuracy: 0.3238 - val_loss: 5.3561 - val_accuracy: 0.3556
Epoch 3/1000
4/4 [==============================] - 0s 51ms/step - loss: 5.7110 - accuracy: 0.3238 - val_loss: 5.0825 - val_accuracy: 0.3556
Epoch 4/1000
4/4 [==============================] - 0s 60ms/step - loss: 5.3961 - accuracy: 0.3238 - val_loss: 4.8187 - val_accuracy: 0.3556
Epoch 5/1000
4/4 [==============================] - 0s 73ms/step - loss: 5.1038 - accuracy: 0.3238 - val_loss: 4.5640 - val_accuracy: 0.3556
Epoch 6/1000
4/4 [==============================] - 0s 59ms/step - loss: 4.8032 - accuracy: 0.3238 - val_loss: 4.3221 - val_accuracy: 0.3556
Epoch 7/1000
4/4 [==============================] - 0s 92ms/step - loss: 4.5231 - accuracy: 0.3238 - val_loss: 4.0855 - val_accuracy: 0.3556
Epoch 8/1000

In [8]:
previsoes = modelo.predict(X_teste)
previsoes = (previsoes > 0.5)

previsoes

2/2 [==============================] - 0s 23ms/step


array([[False, False,  True],
       [False,  True, False],
       [ True, False, False],
       [False, False,  True],
       [ True, False, False],
       [False, False,  True],
       [ True, False, False],
       [False,  True, False],
       [False,  True, False],
       [False,  True, False],
       [False, False,  True],
       [False,  True, False],
       [False,  True, False],
       [False,  True, False],
       [False,  True, False],
       [ True, False, False],
       [False,  True, False],
       [False,  True, False],
       [ True, False, False],
       [ True, False, False],
       [False, False,  True],
       [False,  True, False],
       [ True, False, False],
       [ True, False, False],
       [False, False,  True],
       [ True, False, False],
       [ True, False, False],
       [False,  True, False],
       [False,  True, False],
       [ True, False, False],
       [False, False,  True],
       [False,  True, False],
       [ True, False, False],
       [Fa

In [9]:
y_teste_matrix = [np.argmax(t) for t in y_teste]
y_previsoes_matrix = [np.argmax(t) for t in previsoes]

In [10]:
confusao = confusion_matrix(y_teste_matrix, y_previsoes_matrix)
confusao

array([[16,  0,  0],
       [ 0, 17,  1],
       [ 0,  0, 11]])

In [12]:
taxa_acerto = np.sum(np.diagonal(confusao) / np.sum(confusao))
taxa_acerto

0.9777777777777779