In [1]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
)
import numpy as np
import pandas as pd

In [2]:
mtcars = pd.read_csv("data/mt_cars.csv")

mtcars.head()

Unnamed: 0   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
0          Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4   
1      Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4   
2         Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4   
3     Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3   
4  Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3   

   carb  
0     4  
1     4  
2     1  
3     1  
4     2

In [3]:
X = mtcars[["mpg", "hp"]].values
y = mtcars["cyl"].values

In [4]:
knn = KNeighborsClassifier(n_neighbors=3)

model = knn.fit(X, y)

In [6]:
y_predict = model.predict(X)

print(y_predict)

[6 6 4 6 8 6 8 4 4 6 6 8 8 8 8 8 8 4 4 4 4 8 8 8 8 4 4 4 8 8 8 6]


In [9]:
print("Accuracy: ", accuracy_score(y, y_predict))
print("Precision: ", precision_score(y, y_predict, average="weighted"))
print("Recall: ", recall_score(y, y_predict, average="weighted"))
print("F1 Score: ", f1_score(y, y_predict, average="weighted"))
print("Confusion Matrix: ")
print(confusion_matrix(y, y_predict))

Accuracy:  0.9375
Precision:  0.9395833333333333
Recall:  0.9375
F1 Score:  0.9372947454844006
Confusion Matrix: 
[[10  1  0]
 [ 0  6  1]
 [ 0  0 14]]


In [10]:
# MPG & HP
new_data = np.array([[21, 110], [15, 150], [30, 100]])

new_predict = model.predict(new_data)

#c Cyl
print(new_predict)

[6 8 4]


In [12]:
distances, indices = model.kneighbors(new_data)

print(distances)
print("--------")
print(indices)

[[ 0.          0.          0.4       ]
 [ 0.2         0.5        25.27231687]
 [ 8.7658428   9.01387819  9.8488578 ]]
--------
[[ 0  1  3]
 [22 21  4]
 [ 8 20 26]]
