In [1]:
import numpy as np

#### Matrix operations 

In [2]:
A = np.matrix("1 3 9; 8 5 6 ; 7 8 -5")

A

matrix([[ 1,  3,  9],
        [ 8,  5,  6],
        [ 7,  8, -5]])

In [3]:
B = np.matrix("-5 9 8; 1 1 1 ; 2 2 2")

B

matrix([[-5,  9,  8],
        [ 1,  1,  1],
        [ 2,  2,  2]])

In [4]:
C = np.matrix("1 2 3; 4 5 6 ; 7 8 9")

C

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [5]:
A + B

matrix([[-4, 12, 17],
        [ 9,  6,  7],
        [ 9, 10, -3]])

In [6]:
X = (A + B) + C

X

matrix([[-3, 14, 20],
        [13, 11, 13],
        [16, 18,  6]])

In [7]:
Y = A + (B + C)

Y

matrix([[-3, 14, 20],
        [13, 11, 13],
        [16, 18,  6]])

In [8]:
X == Y

matrix([[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]])

In [9]:
A - B

matrix([[ 6, -6,  1],
        [ 7,  4,  5],
        [ 5,  6, -7]])

In [10]:
B - A

matrix([[-6,  6, -1],
        [-7, -4, -5],
        [-5, -6,  7]])

In [11]:
2 * A

matrix([[  2,   6,  18],
        [ 16,  10,  12],
        [ 14,  16, -10]])

In [12]:
2 * (A + B) == 2 * A + 2 * B

matrix([[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]])

#### Problemas do semáforo (A, B e C)

In [13]:
#         Destino
#            A B C
#         A  0 1 1
# Origem  B  1 0 0
#         C  0 0 0

semaforo1 = np.matrix("0 1 1; 1 0 0; 0 0 0")

semaforo1

matrix([[0, 1, 1],
        [1, 0, 0],
        [0, 0, 0]])

In [14]:
#        Destino
#           A B C
#        A  0 0 0
# Origem B .5 0 .5
#        C  0 .5 0

semaforo2 = np.matrix("0 0 0; .5 0 .5; 0 .5 0")

semaforo2

matrix([[0. , 0. , 0. ],
        [0.5, 0. , 0.5],
        [0. , 0.5, 0. ]])

In [15]:
#       Destino
#          A B C
#        A 0 0 .5
# Origem B 0 0 0
#        C .5 .5 0
semaforo3 = np.matrix("0 0 .5; 0 0 0; .5 .5 0")

semaforo3

matrix([[0. , 0. , 0.5],
        [0. , 0. , 0. ],
        [0.5, 0.5, 0. ]])

In [16]:
tempoTotal = semaforo1 + semaforo2 + semaforo3

tempoTotal

matrix([[0. , 1. , 1.5],
        [1.5, 0. , 0.5],
        [0.5, 1. , 0. ]])

In [17]:
# Quanto tempo cada semáforo fica aberto por hora

tempoTotalHora = tempoTotal * 30

tempoTotalHora

matrix([[ 0., 30., 45.],
        [45.,  0., 15.],
        [15., 30.,  0.]])

In [18]:
# Passam 20 carros por minuto, quantos carros vão passar ao todo?

totalCarrosHora = tempoTotalHora * 20

In [19]:
# Quantos carros foram no total?

np.sum(totalCarrosHora)

3600.0

In [20]:
# Total de carros em cada rua?

np.sum(totalCarrosHora, axis=1)

matrix([[1500.],
        [1200.],
        [ 900.]])

In [21]:
# Total de carros que cada rua recebeu?

np.sum(totalCarrosHora, axis=0)

matrix([[1200., 1200., 1200.]])

#### Multiplicando matrizes

In [22]:
D = np.matrix("1 2 3; 4 5 6; 7 8 9")

D

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [23]:
E = np.matrix("1 2 3")

E

matrix([[1, 2, 3]])

In [24]:
F = np.matrix("1; 2; 3")

F

matrix([[1],
        [2],
        [3]])

In [25]:
D * F

matrix([[14],
        [32],
        [50]])

In [26]:
E * D

matrix([[30, 36, 42]])

#### Deteterminantes

In [27]:
A = np.matrix("1 2; 3 4")

A

matrix([[1, 2],
        [3, 4]])

In [28]:
detA = np.linalg.det(A)

detA

-2.0000000000000004

In [29]:
B = np.matrix("5 6; 7 8")

B

matrix([[5, 6],
        [7, 8]])

In [30]:
detB = np.linalg.det(B)

detB

-1.999999999999999

In [31]:
detAB = np.linalg.det(A * B)
detAB

4.000000000000017

In [32]:
detA * detB

3.9999999999999987

In [33]:
detAB == detA * detB

False

In [34]:
det5A = np.linalg.det(5 * A)

det5A

-50.000000000000014

#### Matriz inversa

In [35]:
invA = np.linalg.inv(A)

invA

matrix([[-2. ,  1. ],
        [ 1.5, -0.5]])

In [36]:
A * invA

matrix([[1.00000000e+00, 1.11022302e-16],
        [0.00000000e+00, 1.00000000e+00]])

In [37]:
detIA = np.linalg.det(invA)

detIA

-0.5000000000000001

#### Matriz Transposta

In [38]:
tA = np.transpose(A)

tA

matrix([[1, 3],
        [2, 4]])

In [39]:
detTA = np.linalg.det(tA)

detTA

-2.0

#### Equação Matricial

In [40]:
A = np.matrix("3 0 0; 1 2 0; 0 1 -1")

A

matrix([[ 3,  0,  0],
        [ 1,  2,  0],
        [ 0,  1, -1]])

In [41]:
B = np.matrix("30; 18; 2")

B

matrix([[30],
        [18],
        [ 2]])

In [42]:
invA = np.linalg.inv(A)

invA

matrix([[ 0.33333333,  0.        ,  0.        ],
        [-0.16666667,  0.5       ,  0.        ],
        [-0.16666667,  0.5       , -1.        ]])

In [43]:
matrixS = invA * B

matrixS

matrix([[10.],
        [ 4.],
        [ 2.]])

#### Criptografia com matriz

In [44]:
M = np.matrix(" 1 3 18 5 4 9 20 5 28; 5 13 28 22 15 3 5 27 28")

M

matrix([[ 1,  3, 18,  5,  4,  9, 20,  5, 28],
        [ 5, 13, 28, 22, 15,  3,  5, 27, 28]])

In [46]:
A = np.matrix("3 1; 2 1")

A

matrix([[3, 1],
        [2, 1]])

In [47]:
invA = np.linalg.inv(A)

invA

matrix([[ 1., -1.],
        [-2.,  3.]])

In [48]:
AM = A * M

AM

matrix([[  8,  22,  82,  37,  27,  30,  65,  42, 112],
        [  7,  19,  64,  32,  23,  21,  45,  37,  84]])

In [50]:
M2 = invA * AM

M2

matrix([[ 1.,  3., 18.,  5.,  4.,  9., 20.,  5., 28.],
        [ 5., 13., 28., 22., 15.,  3.,  5., 27., 28.]])

#### Calculo de atividades Fisicas com matriz

In [52]:
A = np.matrix("1 0 0 1; 0 0 1 0; 0.5 0.5 0 0 ; 0 0 0.5 0.5; 0.5 1 0 0")

A

matrix([[1. , 0. , 0. , 1. ],
        [0. , 0. , 1. , 0. ],
        [0.5, 0.5, 0. , 0. ],
        [0. , 0. , 0.5, 0.5],
        [0.5, 1. , 0. , 0. ]])

In [53]:
B = np.matrix("252; 552; 890; 300")

B

matrix([[252],
        [552],
        [890],
        [300]])

In [54]:
gasto = A * B

gasto

matrix([[552.],
        [890.],
        [402.],
        [595.],
        [678.]])

#### Cadeias de Markov

In [55]:
P = np.matrix("0.7 0.15 0.15; 0.2 0.8 0.15; 0.1 0.05 0.7")

P

matrix([[0.7 , 0.15, 0.15],
        [0.2 , 0.8 , 0.15],
        [0.1 , 0.05, 0.7 ]])

In [58]:
X0 = np.matrix("0.15; 0.2; 0.65")

X0

matrix([[0.15],
        [0.2 ],
        [0.65]])

In [59]:
X1 = P * X0

X1

matrix([[0.2325],
        [0.2875],
        [0.48  ]])

In [60]:
X1 * 100000

matrix([[23250.],
        [28750.],
        [48000.]])

In [62]:
X3 = (P**3) * X0

X3

matrix([[0.30283125],
        [0.39041875],
        [0.30675   ]])

In [63]:
X5 = (P**5) * X0

X5

matrix([[0.32410645],
        [0.4381218 ],
        [0.23777175]])

In [64]:
X10 = (P**10) * X0

X10

matrix([[0.33286896],
        [0.4714703 ],
        [0.19566074]])

In [65]:
X15 = (P**15) * X0

X15

matrix([[0.33330996],
        [0.47562754],
        [0.19106249]])

#### Aplicação do produto escalar

In [66]:
# CPF: 313.402.809-30

A = (3, 1, 3, 4, 0, 2, 8, 0, 9)
B = (10, 9, 8, 7, 6, 5, 4, 3, 2)

In [67]:
# Produto escalar dos vetores A e B
PE = (
    A[0] * B[0]
    + A[1] * B[1]
    + A[2] * B[2]
    + A[3] * B[3]
    + A[4] * B[4]
    + A[5] * B[5]
    + A[6] * B[6]
    + A[7] * B[7]
    + A[8] * B[8]
)

PE

151

In [79]:
resto = PE % 11

resto

8

In [74]:
# Primeiro digito verificador

if resto < 2:
    dv1 = 0
else:
    dv1 = 11 - resto

# CPF: 313.402.809-30
dv1 == 3

True

In [75]:
C = (3, 1, 3, 4, 0, 2, 8, 0, 9, 3)
D = (11, 10, 9, 8, 7, 6, 5, 4, 3, 2)

PE2 = (
    C[0] * D[0]
    + C[1] * D[1]
    + C[2] * D[2]
    + C[3] * D[3]
    + C[4] * D[4]
    + C[5] * D[5]
    + C[6] * D[6]
    + C[7] * D[7]
    + C[8] * D[8]
    + C[9] * D[9]
)

PE2

187

In [78]:
resto2 = PE2 % 11

resto2

0

In [81]:
# Segundo digito verificador

if resto2 < 2:
    dv2 = 0
else:
    dv2 = 11 - resto2

# CPF: 313.402.809-30
dv2 == 0

True